#!/usr/bin/env bash
# compliance-review.sh — weekly legal/public-records brief.
#
# REPORT-ONLY by design. It emits no GEMINI_*.md specs, so it never competes with
# engineering work for implementation slots, and it does not chain into the phase
# pipeline. Its subject matter is deliberately not automatable: the highest-value
# items in ROADMAP Phase 0 are a phone call, a records request, and reading the
# portal's terms of use. This brief tells a human what to do, not a machine.
#
# Deliberately off the phase-chain schedule so it never starts alongside one.
set -uo pipefail

PROJECT_DIR="/home/san/Workspaces/county_crawler"
source "${PROJECT_DIR}/scripts/pipeline_id.sh" || exit 1
REVIEW_DIR="${PROJECT_DIR}/reviews"
source "${PROJECT_DIR}/scripts/agent_cost.sh"
DATE="${PIPELINE_DATE}"
OUTPUT_FILE="${REVIEW_DIR}/${PIPELINE_ID}-compliance.md"
CLAUDE="${CLAUDE_BIN:-claude}"
LOG_FILE="${REVIEW_DIR}/${PIPELINE_ID}-compliance.log"

mkdir -p "${REVIEW_DIR}"
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "${LOG_FILE}"; }

PHASE="compliance-review"
HEALTH_LOG="${REVIEW_DIR}/pipeline-health.log"
health_log() { echo "$(date '+%Y-%m-%d %H:%M:%S') ${PIPELINE_ID} ${PHASE} $*" >> "${HEALTH_LOG}"; }
trap 'rc=$?; if [ "${rc}" -eq 0 ]; then health_log PASS; else health_log "FAIL exit=${rc}"; fi' EXIT
health_log START

if [ -f "${OUTPUT_FILE}" ]; then
    log "Compliance brief already exists for ${PIPELINE_ID} — skipping"
    exit 0
fi

log "Starting compliance review (${PIPELINE_ID})"

PRIOR=""
LATEST=$(ls -t "${REVIEW_DIR}"/*-compliance.md 2>/dev/null | head -1)
[ -n "${LATEST}" ] && PRIOR=$(cat "${LATEST}")

PROMPT="Produce this week's compliance and public-records brief for county_crawler.

Priorities, in order:
1. The Recorder bulk-data route (209-468-3939) and, failing that, a CPRA request
   under Government Code §6253.9. Say exactly what to ask for and in what order.
   Bulk data could obsolete both the portal path and the parcel bridge.
2. The portal's terms of use, including the indemnification clause accepted by
   clicking through the disclaimer. This has not been read and is the item most
   likely to change what is permissible. Say what to look for.
3. The SB 272 Enterprise System Catalog for San Joaquin County.
4. Representation limits: what may honestly be claimed about this data, given the
   recorder calls the grantor/grantee index a finding aid, prices are DERIVED
   from transfer tax rather than recorded (§6.4), and there is no address or APN
   (§6.3).

Name your sources so they can be looked up, and mark clearly what you confirmed
versus what you inferred. If a prior brief exists below, do not repeat it —
report what changed or what you can now confirm.

Never recommend defeating, automating, or circumventing the CAPTCHA or the
disclaimer gate, or any technique whose purpose is avoiding detection. If the
terms prohibit automated access, the correct recommendation is the public-records
route, not stealthier scraping.

Report-only: do NOT create or edit any GEMINI_*.md spec, and do not edit repo
files. Under 800 words. Include the standard not-legal-advice disclaimer.

--- PRIOR BRIEF ---
${PRIOR:-none}"

STDERR_FILE=$(mktemp)
RAW=$(cd "${PROJECT_DIR}" && printf '%s' "${PROMPT}" | "${CLAUDE}" -p \
    --agent legal-compliance \
    --dangerously-skip-permissions \
    --model sonnet \
    --effort medium \
    --max-budget-usd 2.00 \
    --output-format json \
    2>"${STDERR_FILE}") || true
OUTPUT=$(agent_cost_capture_result "compliance-review" "legal-compliance" "sonnet" "${RAW}")

if [ -s "${STDERR_FILE}" ]; then
    log "claude stderr:"
    cat "${STDERR_FILE}" >> "${LOG_FILE}"
fi
rm -f "${STDERR_FILE}"

if [ -z "${OUTPUT}" ]; then
    log "ERROR: compliance agent returned empty output"
    cat > "${OUTPUT_FILE}" <<EOF
# Compliance Brief — ${DATE}

**FAILED**: agent returned empty output. See ${LOG_FILE}.
EOF
    exit 1
fi

cat > "${OUTPUT_FILE}" <<EOF
# Compliance Brief — ${DATE}

_Auto-generated by compliance-review.sh at $(date '+%Y-%m-%d %H:%M:%S')_
_Report-only. Not legal advice. No specs emitted._

---

${OUTPUT}
EOF

log "Compliance brief → ${OUTPUT_FILE}"

# Take the lock only to commit — the agent run itself does web research and is
# slow, and holding the lock across it would block a whole phase chain.
exec 9>"${PROJECT_DIR}/.pipeline.lock"
if flock -w 300 9; then
    cd "${PROJECT_DIR}"
    git add "reviews/$(basename "${OUTPUT_FILE}")" reviews/pipeline-health.log 2>>"${LOG_FILE}" || true
    if ! git diff --cached --quiet 2>/dev/null; then
        git commit -m "docs: compliance brief ${PIPELINE_ID}" >>"${LOG_FILE}" 2>&1 \
            || log "WARNING: commit failed"
    fi
else
    log "WARNING: could not take the lock to commit — brief is on disk, uncommitted"
fi
